# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  dockerId: capkenr
  dockerPassword: igDuMJoj7QqQHKk9YgLN
  imageName: 'helloworld:$(build.buildId)'

steps:
- script: |
    docker image build -t $(dockerId)/$(imageName) .
    docker login -u $(dockerId) -p $(dockerPassword)
    docker image push $(dockerId)/$(imageName)
